### ISSUE TITLE
Documentation: Configuration

### ISSUE THREAD

**Issue by amenk** [trufi-association/trotro-app#3]
I tried adding an assets/cfg/app_config.json but when starting the app I get

	Installing build/app/outputs/apk/app.apk...                         1.9s
	D/EGL_emulation(27348): eglMakeCurrent: 0xec840080: ver 2 0 (tinfo 0xe5114c10)
	E/flutter (27348): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Unable to load asset: assets/cfg/app_config.json
	E/flutter (27348): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
	E/flutter (27348): <asynchronous suspension>
	E/flutter (27348): #1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:67:33)

and it does not go past the splash screen.

What am I doing wrong? We should have documentation for that ... ;-)

**Comment by amenk** [comment]
`flutter clean` and `flutter run` seems to help - it seems it did not pick up the new directory I created
